### ISSUE TITLE
mugshot

### ISSUE THREAD

**Issue by markvdb** [jrial/fosdem-volunteers#38]
(as per Richard's request on fit@)

Please make it as easy and obvious as possible to upload one's picture and phone number during the signup process. Add extremely clear information about what it's going to be used for. Make it clear that if we need to choose between having their mugshot/phone number, we'd rather have them volunteer.

Example from the emails sent out to volunteers:
"Phone number and mugshot are used for two purposes only:
* a yearly call to filter volunteers who want to stay listed
* quick practical on-site contact during the conference . Of course,
you are welcome to volunteer without passing us your mobile phone
information too!"

![volunteers_profile_info](https://cloud.githubusercontent.com/assets/778760/6008937/a34a58e4-ab25-11e4-92b2-08c7277abb37.png)

**Comment by jrial** [comment]
Closing this word salad since it's already easy to do, and they already get reminders if they have no mugshot.

Also, this is not Richard's request at fit; that is about showing mugshots in the admin interface, and an overhaul of said interface.

You're free to open a new ticket for the second part of this one, which deals with better wording regarding the goal of having a mugshot. But you already fixed that in the registration mail (see f8d61ab0), and the notification bubbles are not the place for long-winded explanations.
